[phases.build]
cmds = ["npm run build"]

[phases.install]
cmds = ["npm install"]

[phases.start]
cmds = ["npm start"]

[variables]
NODE_VERSION = "20.12.0"

[env]
NODE_OPTIONS = "--max-old-space-size=4096"
